extends RefCounted

## THE MINER'S LIMBS, AS DATA (split from `tools/bake_miner.gd` at the file cap, D0399): every arm and leg
## block, ASCII over the palette in `miner_body.gd`. Legacy verbatim plus `dig_mid`, the level mid-swing.

## ARMS: rows start at y=12 (ARM_TOP) so a raised arm can reach face height, and a block may run as long
## as it likes; dig_down's pick keeps going down past the hips. Stamped LAST, over everything, because
## the near arm is the nearest thing to the camera. Only non-'.' cells are written, so the torso shows
## through everywhere an arm is not.
const ARMS: Dictionary = {
	# At rest, hanging down the front of the coat. Every arm carries 'h' on its leading edge, a full step
	# lighter than the torso it hangs over, which is the only thing that stops it disappearing into the coat.
	"rest": [
		"", "", "", "", "", "", "",
		".......khhk",
		"......khlbk",
		"......khlbk",
		"......khlbk",
		"......khlbk",
		"......klbdk",
		"......klbdk",
		"......klbdk",
		"......klbdk",
		"......kCCCk",
		"......kSssk",
		"......kSssk",
		".......kkk",
	],
	# Swung forward, ahead of the body.
	"fore": [
		"", "", "", "", "", "", "",
		".......khhk",
		"......khlbk",
		".....khlbk",
		".....khlbk",
		"....klbdk",
		"....klbdk",
		"...klbdk",
		"...kCCCk",
		"...kSssk",
		"...kSssk",
		"....kkk",
	],
	# Swung back, across the chest.
	"back": [
		"", "", "", "", "", "", "",
		".......khhk",
		".......khlbk",
		"........khlbk",
		"........khlbk",
		".........klbdk",
		".........klbdk",
		"..........klbdk",
		"..........kCCCk",
		"..........kSssk",
		"..........kSssk",
		"...........kkk",
	],
	# Up and forward: reaching for a line that is above and ahead of him.
	"reach": [
		"", "",
		"..kSssk",
		"..kSssk",
		"..kCCCk",
		"...khbk",
		"....khbk",
		".....klbk",
		"......khhk",
	],
	# Straight up: a fist closed on a rope directly overhead.
	"grip": [
		"",
		".....kSsk",
		".....kSsk",
		".....kCCk",
		".....khbk",
		".....khbk",
		".....klbk",
		".....klbk",
		"......khhk",
	],
	# Folded in hard, fist up at the chin: the frame right after a pull, which is what reeling looks like.
	"haul": [
		"", "", "",
		"....kSssk",
		"....kSssk",
		"....kCCCk",
		"...khbk",
		"...khbk",
		"....klbk",
		".....klbk",
		"......khhk",
	],
	# Pick cocked up and forward, both hands on the haft.
	"dig_up": [
		"",
		".kkkkkk",
		"kNNnnnnk",
		"kNnnnnnk",
		".kknnnkk",
		"...khbbk",
		"...kSssk",
		"...kCCCk",
		"....klbk",
		".....khhk",
	],
	# ...and driven down through the swing, head buried below the knee.
	# Mid-swing: the arm straight out ahead at chest height, the pick's head leading, haft level. Between
	# the wind-up over the shoulder and the strike below the hips this is the frame the eye reads as
	# motion, and without it the stroke was two stills.
	"dig_mid": [
		"", "", "", "", "", "",
		"......khhk",
		".....klbbk",
		"....klbbk",
		"...kCCCk",
		"..kSsssk",
		"kkkkkkkkhbbk",
		"kNNnnnnnhbbk",
		"kNnnnnnnkkk",
		".kknnnkk",
	],
	"dig_down": [
		"", "", "", "", "", "", "",
		"......khhk",
		".....klbk",
		"....klbk",
		"....kCCk",
		"...kSssk",
		"...kSssk",
		"...khbbk",
		"..khbbk",
		"..khbbk",
		".khbbk",
		".khbbk",
		".khbbk",
		".kkkkkk",
		"kNNnnnnk",
		"kNnnnnnk",
		".kknnnkk",
	],
}

## LEGS: rows start at y=34 (LEG_TOP). The near leg carries the lit edge 'l' on its front, the far leg
## carries 'd' on its back, so even when the two overlap you can tell which is which. Every grounded pose
## puts a sole on row 47: the bottom of the sprite, which is the bottom of the collider.
const LEGS: Dictionary = {
	"stand": [
		".........kbbbbkbbddk",
		".........klbbbkbdddk",
		".........klbbbkbdddk",
		".........klbbbkbdddk",
		".........klbbbkbdddk",
		".........klbbbkbdddk",
		".........kdbbbkbdddk",
		".........kdbbbkbdddk",
		".........kSssskSsssk",
		".........kSssskSsssk",
		"........kSsssskSsssk",
		".......kSssssskSsssk",
		".......kSssssskSsssk",
		".......kkkkkkkkkkkkk",
	],
	# Contact pose A: near leg planted forward, far leg planted back. Both soles down.
	"stride_a": [
		".........kbbbbkbbddk",
		"........klbbbkkbbddk",
		"........klbbbk.kbbddk",
		".......klbbbk..kbbddk",
		".......klbbbk...kbdddk",
		"......klbbbk....kbdddk",
		"......kdbbbk....kbdddk",
		".....kdbbbk.....kbdddk",
		".....kSsssk.....kSsssk",
		".....kSsssk.....kSsssk",
		"....kSssssk....kSssssk",
		"...kSsssssk....kSssssk",
		"...kSsssssk....kSssssk",
		"...kkkkkkkk....kkkkkkk",
	],
	# Contact pose B: the same stride with the roles swapped; far leg leads, so the lit edge moves.
	"stride_b": [
		".........kbbbbkbbddk",
		"........kdbbbkklbbbk",
		"........kdbbbk.klbbbk",
		".......kdbbbk..klbbbk",
		".......kdbbbk...klbbbk",
		"......kdbbbk....klbbbk",
		"......kdbbbk....klbbbk",
		".....kdbbbk.....klbbbk",
		".....kSsssk.....kSsssk",
		".....kSsssk.....kSsssk",
		"....kSssssk....kSssssk",
		"...kSsssssk....kSssssk",
		"...kSsssssk....kSssssk",
		"...kkkkkkkk....kkkkkkk",
	],
	# Pass A: near leg swinging through, lifted clear of the floor; far leg holds the weight.
	"pass_a": [
		".........kbbbbkbbddk",
		".........klbbbkbdddk",
		".........klbbbkbdddk",
		"........klbbbkkbdddk",
		"........klbbbkkbdddk",
		".......kdbbbk.kbdddk",
		".......kdbbbk.kbdddk",
		".......kSsssk.kbdddk",
		".......kSsssk.kSsssk",
		"......kSssssk.kSsssk",
		"......kkkkkkk.kSsssk",
		"..............kSsssk",
		"..............kSsssk",
		"..............kkkkkk",
	],
	# Pass B: the mirror; far leg swings through behind him, near leg holds the weight. Having two
	# different pass frames is what stops walk_1 and walk_3 from being the same picture twice.
	"pass_b": [
		".........kbbbbkbbddk",
		".........klbbbkbdddk",
		".........klbbbkbdddk",
		".........klbbbkkbdddk",
		".........klbbbkkbdddk",
		".........klbbbk.kbdddk",
		".........klbbbk.kbdddk",
		".........klbbbk.kbdddk",
		".........kSsssk.kSsssk",
		"........kSssssk.kSsssk",
		".......kSsssssk.kSsssk",
		".......kSsssssk.kkkkkk",
		".......kSsssssk",
		".......kkkkkkkk",
	],
	# Tucked: knees up and forward. Rising.
	"tuck": [
		".........kbbbbkbbddk",
		"........klbbbkkbbddk",
		".......klbbbk.kbbddk",
		"......klbbbk..kbbddk",
		".....kdbbbk...kbdddk",
		".....kSsssk...kbdddk",
		"....kSsssk....kbdddk",
		"....kkkkkk....kSsssk",
		"..............kSsssk",
		".............kSssssk",
		".............kkkkkkk",
	],
	# Braced wide and bent, absorbing a landing.
	"brace": [
		".........kbbbbkbbddk",
		"........klbbbkkbbddk",
		".......klbbbk..kbbddk",
		"......klbbbk...kbbddk",
		".....kdbbbk....kbbddk",
		"....kdbbbk......kbdddk",
		"...kdbbbk.......kbdddk",
		"...kSsssk.......kbdddk",
		"..kSsssk........kSsssk",
		"..kSsssk........kSsssk",
		".kSssssk........kSssssk",
		".kSssssk........kSssssk",
		".kSssssk........kSssssk",
		".kkkkkkk........kkkkkkk",
	],
	# Streaming back: nothing under him, everything trailing. Falling, or swung out on a taut line.
	"trail": [
		".........kbbbbkbbddk",
		".........klbbbkbdddk",
		"..........klbbbkbdddk",
		"..........klbbbkbdddk",
		"...........klbbbkbdddk",
		"...........klbbbkbdddk",
		"............klbbbkbdddk",
		"............klbbbkbdddk",
		"............kSssskSsssk",
		"............kSssskSsssk",
		"...........kSsssskSsssk",
		"...........kSsssskSsssk",
		"...........kkkkkkkkkkkk",
	],
	# Straight down and closed up: dead weight on a line.
	"hang": [
		".........kbbbbkbbddk",
		"..........klbbkbddk",
		"..........klbbkbddk",
		"..........klbbkbddk",
		"..........klbbkbddk",
		"..........kdbbkbddk",
		"..........kdbbkbddk",
		"..........kdbbkbddk",
		"..........kSsskSssk",
		"..........kSsskSssk",
		".........kSssskSssk",
		".........kSssskSssk",
		".........kkkkkkkkkk",
	],
	# One knee driven up, the other hanging: the shape of going UP a rope rather than dangling on it.
	"climb": [
		".........kbbbbkbbddk",
		"........klbbbkkbdddk",
		".......klbbbk.kbdddk",
		"......klbbbk..kbdddk",
		"......kSsssk..kbdddk",
		"......kSsssk..kbdddk",
		"......kkkkkk..kbdddk",
		"..............kbdddk",
		"..............kSsssk",
		"..............kSsssk",
		".............kSssssk",
		".............kSssssk",
		".............kkkkkkk",
	],
}
