#!/usr/bin/env python3
"""Module doc presence. docs/QUALITY.md gate 6.

    python3 tools/layer_lint/check_module_docs.py [--root DIR]

Every directory holding `.gd` files inside a policed layer (the layers `layer_lint.py`'s `ALLOWED`
models) must carry a module doc: `MODULE.md` (the `core`/`interface`/`sim` convention) or `README.md`
(the `view`/`shell`/`harness` convention -- the tree practices both, so this gate checks for a doc,
not a filename).

`data/` is exempt: its subdirs are generated catalog shards written by `tools/data_codegen` (ADR
0004); a hand doc in `data/<record>/` would describe the generator's output, which the generator's
provenance comments and the ADR already carry.

`layer_of()` returns None for unpoliced tops (`tests/`, `playtest/`, `legacy/`, `tools/`), so those
dirs are out of scope by the same rule that keeps them out of the dependency graph -- a directory the
architecture does not model is not a "module directory" this gate can honestly require a doc for.

PRESENCE ONLY. Gate 6's text also says "current"; content freshness is not a property a cheap check
can verify and is not claimed here -- the gate text says so too.

Exit 0 = every in-scope directory carries a doc. Exit 1 = at least one does not, printed above the
summary. Exit 2 = the scan found no policed `.gd`-bearing directories at all, which is a report about
this tool's population, not the tree.
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gd_scan import gd_files_excluding  # noqa: E402
from layer_lint import UNPOLICED, layer_of  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]

DOC_NAMES = ("MODULE.md", "README.md")

# `data/<record>/generated.gd` is regenerated by tools/data_codegen (ADR 0004). Each subdir is one
# shard of a single generated catalog, not a module; its documentation is the generator and the ADR.
EXEMPT_LAYERS = {"data"}


def dirs_missing_doc(root: Path, rel_files) -> tuple:
    """(missing, required): the sorted in-scope parent directories among `rel_files` carrying neither
    MODULE.md nor README.md under `root`, and how many in-scope directories were required."""
    required = set()
    for rel in rel_files:
        layer = layer_of(rel)
        if layer is None or layer in EXEMPT_LAYERS:
            continue
        required.add(rel.parent)
    missing = [d for d in sorted(required)
               if not any((root / d / name).is_file() for name in DOC_NAMES)]
    return missing, len(required)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args()
    root = args.root.resolve()

    rel_files = list(gd_files_excluding(root, UNPOLICED))
    missing, required = dirs_missing_doc(root, rel_files)
    if required == 0:
        print("check_module_docs: FAIL (tool) -- no policed .gd-bearing directories found; the scan "
              "population is empty, which says something about this tool, not the tree.")
        return 2
    for d in missing:
        print(f"check_module_docs: FAIL -- {d}/ holds .gd files but neither MODULE.md nor README.md")
    print(f"check_module_docs: {required} .gd-bearing directories in policed layers, "
          f"{len(missing)} missing a module doc")
    if missing:
        return 1
    print("check_module_docs: PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
